language: cpp

compiler:
- clang
- gcc


before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- |
  if [ "$CXX" = "clang" ]; then
    sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-4.0-binaries main' >> /etc/apt/sources.list"
    sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
    wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  fi
- sudo apt install qt5-default libqt5charts5 libqt5charts5-dev -y

install:
- sudo apt-get install -qq g++-5 gcc-5
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- |
  if [ "$CXX" = "clang" ]; then
    sudo apt-get install -qq llvm-4.0
    export CXX="clang++" CC="clang"
  fi
- $CXX --version

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
- make -j4
