language: cpp

compiler:
- clang
- gcc

env:
- QT_BASE=57
- QT_BASE=58
- QT_BASE=59
- QT_BASE=510


matrix:
  allow_failures:
  - compiler: clang
    env: QT_BASE=57
  - compiler: clang
    env: QT_BASE=58

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- |
  if [ "$CXX" = "clang" ]; then
    sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-4.0-binaries main' >> /etc/apt/sources.list"
    sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
    wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  fi
- if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
- if [ "$QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi
- if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y; fi
- if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y; fi
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-5 gcc-5
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- |
  if [ "$CXX" = "clang" ]; then
    sudo apt-get install -qq llvm-4.0
    export CXX="clang++" CC="clang"
  fi
- $CXX --version
- sudo apt-get install -qq qt${QT_BASE}base qt${QT_BASE}script; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
- make -j4
