# Copyright(c) 2018 Asit Dhal.
# Distributed under the MIT License (http://opensource.org/licenses/MIT)

language: cpp
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

configuration:
  - Release
  - Debug

environment:
  matrix:
    - CMAKE_BUILD_SYS: true
    - QMAKE_BUILD_SYS: true


matrix:
  include:
  - os: osx
    osx_image: xcode9
    compiler: clang
  - os: linux
    compiler: gcc
    env:
      - CXX_COMPILER=g++-7
      - C_COMPILER=gcc-7
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test"]
        packages: ["g++-7", "ninja-build"]
  - os: linux
    compiler: clang
    env:
      - CXX_COMPILER=clang++-5.0
      - C_COMPILER=clang-5.0
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"]
        packages: ["clang-5.0", "g++-7", "ninja-build"]

before_install:
  - export CXX=${CXX_COMPILER}
  - export CC=${C_COMPILER}

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y; 
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
      brew cleanup;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -qq qt510base qt510charts-no-lgpl; source /opt/qt510/bin/qt510-env.sh;
    else
        brew install qt5;
        brew link --force qt5;
        export HOMEBREW_QT5_VERSION=$(brew list --versions qt5 | rev | cut -d' ' -f1 | rev);
        sudo ln -s /usr/local/Cellar/qt5/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
        echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile;
    fi

script:
  - mkdir ./build && cd ./build
  - if [ "$CMAKE_BUILD_SYS" = "true" ]; then
      cmake --version;
      cmake -DCMAKE_BUILD_TYPE=$configuration ..;
      make -j2;
    else
      qmake -v;
      qmake ../BenchmarkViewer.pro CONFIG+=$configuration;
      make -j2 ;
    fi

notifications:
email: false
