version: '{build}'

init:
- git config --global core.autocrlf input

branches:
  only:
    - master
    - dev


environment:
  matrix:
  - QT5: C:\Qt\5.7\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    use_cmake: "false"
  - QT5: C:\Qt\5.8\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    use_cmake: "false"
  - QT5: C:\Qt\5.9\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    use_cmake: "false"
  - QT5: C:\Qt\5.10.1\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    use_cmake: "false"

matrix:
  fast_finish: true

before_build:
- set PATH=%MINGW%\bin;%QT5%\bin;%PATH%

build_script:
- mkdir .\build
- cd .\build

# build library and binary
- if [%use_cmake%]==[true] (
    cmake --version &&
    cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .. &&
    make &&
    dir /s &&
    cd .\example)
  else (
    qmake -v &&
    qmake ..\BenchmarkViewer.pro CONFIG+=release DESTDIR=%cd% &&
    mingw32-make)

after_build:
  - mkdir bin
  - copy BenchmarkViewer.exe bin\
  - windeployqt bin\BenchmarkViewer.exe
  - 7z a BenchmarkViewer.7z bin\*
  - dir

artifacts:
  - path: build\BenchmarkViewer.7z
    name: BenchmarkViewer
